import { useEffect, useMemo, useState } from 'react';
import { Check, Plus, ShoppingBasket, Trash2 } from 'lucide-react';
import { api } from '../lib/api';
import { PageHeader } from '../components/PageHeader';
import { Modal } from '../components/Modal';

export function ShoppingListPage() {
  const [items, setItems] = useState([]);
  const [name, setName] = useState('');
  const [note, setNote] = useState('');
  const [loading, setLoading] = useState(true);

  // #3: 체크 시 구매내역 등록을 위한 모달
  const [checkModal, setCheckModal] = useState(null); // 체크 대상 item
  const [checkPrice, setCheckPrice] = useState('');
  const [checkGrams, setCheckGrams] = useState('200');
  const [confirming, setConfirming] = useState(false);

  const load = async () => {
    setLoading(true);
    try { const res = await api.get('/shopping-list'); setItems(res.data); }
    finally { setLoading(false); }
  };
  useEffect(() => { load(); }, []);

  const addItem = async (event) => {
    event.preventDefault();
    if (!name.trim()) return;
    await api.post('/shopping-list', { name, note });
    setName(''); setNote('');
    await load();
  };

  // #3: 체크 클릭 → 수동 항목이면 가격/그램 입력 모달, 자동 추천이면 바로 토글
  const handleToggle = (item) => {
    if (item.checked) {
      // 체크 해제는 즉시 처리
      api.patch(`/shopping-list/${item.id}`, { checked: false }).then(load);
      return;
    }
    if (item.autoGenerated) {
      // 자동 추천 항목은 단순 체크/해제만
      api.patch(`/shopping-list/${item.id}`, { checked: true }).then(load);
      return;
    }
    // 수동 등록 항목 → 구매내역 반영을 위한 모달 오픈
    setCheckModal(item);
    setCheckPrice('');
    setCheckGrams('200');
  };

  const confirmCheck = async () => {
    if (!checkModal) return;
    setConfirming(true);
    try {
      await api.patch(`/shopping-list/${checkModal.id}`, {
        checked: true,
        price: Number(checkPrice) || 0,
        grams: Number(checkGrams) || 200,
      });
      setCheckModal(null);
      await load();
    } finally { setConfirming(false); }
  };

  const removeItem = async (id) => { await api.delete(`/shopping-list/${id}`); await load(); };

  // ════════════════════════════════════════════════════════════════
  // 기능 2: 자동 추천 항목 → 실제 체크리스트로 즉시 등록(Upsert)
  // ════════════════════════════════════════════════════════════════
  // 추천 항목의 "+" 버튼을 누르면 서버가 동일 이름의 수동(checked 가능한)
  // 항목을 찾아 재사용하거나 새로 생성한다. 추천 row 자체는 그대로 유지되며,
  // "내 체크리스트" 섹션에 새 항목이 즉시 동기화되어 나타난다.
  const [adoptingId, setAdoptingId] = useState(null);
  const [adoptedMsg, setAdoptedMsg] = useState('');
  const adoptToChecklist = async (item) => {
    setAdoptingId(item.id);
    try {
      const res = await api.post('/shopping-list/adopt', { name: item.name, note: item.note });
      setAdoptedMsg(res.data.created ? `'${item.name}'을(를) 체크리스트에 추가했어요.` : `'${item.name}'은(는) 이미 체크리스트에 있어요.`);
      setTimeout(() => setAdoptedMsg(''), 2500);
      await load();
    } finally { setAdoptingId(null); }
  };

  // #2: 자동 추천(일시적) / 수동 체크리스트 분리
  const autoItems = useMemo(() => items.filter(i => i.autoGenerated), [items]);
  const manualItems = useMemo(() => items.filter(i => !i.autoGenerated), [items]);

  const stats = useMemo(() => ({
    auto: autoItems.filter(i => !i.checked).length,
    manual: manualItems.filter(i => !i.checked).length,
    done: items.filter(i => i.checked).length,
  }), [items, autoItems, manualItems]);

  return (
    <div>
      <PageHeader title="장보기 체크리스트" subtitle="직접 등록한 체크리스트는 구매 완료 시 자동으로 구매내역에 반영됩니다." />

      <div className="grid gap-6 lg:grid-cols-3">
        <section className="soft-card h-fit p-6">
          <div className="flex items-center gap-3 border-b border-border pb-4">
            <div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-[#EDF7E7] text-sage"><ShoppingBasket size={20} /></div>
            <div>
              <h2 className="text-xl font-bold text-slate-900">구매할 식재료 입력</h2>
              <p className="text-sm text-slate-500">필요한 장보기 물품을 간편하게 리스트에 기록합니다.</p>
            </div>
          </div>

          <form onSubmit={addItem} className="mt-4 space-y-4">
            <input required value={name} onChange={(e) => setName(e.target.value)} className="input-base" placeholder="식재료 명칭 (예: 닭가슴살 2팩)" />
            <input value={note} onChange={(e) => setNote(e.target.value)} className="input-base" placeholder="추가 메모 또는 브랜드 (선택)" />
            <button type="submit" className="flex w-full items-center justify-center gap-2 rounded-2xl bg-sage px-5 py-3.5 font-bold text-white transition-all hover:bg-opacity-95">
              <Plus size={18} /> 품목 리스트 추가
            </button>
          </form>

          <div className="mt-6 grid grid-cols-3 gap-2 text-center text-sm">
            <div className="rounded-2xl bg-[#F4F8F1] p-3"><div className="font-bold text-sage">{stats.auto}개</div><div className="mt-1 text-xs text-slate-500">자동 추천</div></div>
            <div className="rounded-2xl bg-slate-50 p-3"><div className="font-bold text-slate-700">{stats.manual}개</div><div className="mt-1 text-xs text-slate-500">직접 등록</div></div>
            <div className="rounded-2xl bg-slate-50 p-3"><div className="font-bold text-slate-400 line-through">{stats.done}개</div><div className="mt-1 text-xs text-slate-500">구매 완료</div></div>
          </div>

          {/* #2: 직접 등록 체크리스트 — "구매할 식재료 입력" 폼 바로 하단에 배치 */}
          <div className="mt-6 border-t border-border pt-5">
            <div className="mb-3 flex items-center justify-between">
              <h3 className="text-sm font-bold text-slate-700">📝 내 체크리스트</h3>
              <span className="text-xs text-slate-400">터치하면 구매 완료 처리</span>
            </div>
            {manualItems.length === 0 ? (
              <div className="rounded-2xl bg-[#FCFCFC] py-6 text-center text-sm text-slate-400">아직 등록한 항목이 없어요.</div>
            ) : (
              <div className="space-y-2">
                {manualItems.map(item => (
                  <div key={item.id}
                    className={`flex items-center justify-between gap-3 rounded-2xl border px-4 py-3 transition-all ${item.checked ? 'border-transparent bg-slate-100 opacity-60' : 'border-border bg-white hover:border-sage'}`}>
                    <button onClick={() => handleToggle(item)} className="flex flex-1 items-center gap-3 text-left">
                      <span className={`flex h-9 w-9 shrink-0 items-center justify-center rounded-full transition-all ${item.checked ? 'bg-sage text-white' : 'bg-slate-100 text-slate-400'}`}>
                        <Check size={16} />
                      </span>
                      <div className="min-w-0">
                        <div className={`font-semibold truncate ${item.checked ? 'text-slate-400 line-through' : 'text-slate-900'}`}>{item.name}</div>
                        {item.note && <div className="text-xs text-slate-400 truncate">{item.note}</div>}
                      </div>
                    </button>
                    <button onClick={() => removeItem(item.id)} className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-white text-slate-400 hover:text-coral shadow-sm">
                      <Trash2 size={14} />
                    </button>
                  </div>
                ))}
              </div>
            )}
          </div>
        </section>

        <section className="lg:col-span-2">
          {loading ? (
            <div className="soft-card p-8 text-center text-slate-400">장보기 내역을 가져오는 중입니다...</div>
          ) : (
            <div className="space-y-6">
              {/* #2: 자동 추천 — 일시적 안내 영역으로 분리 표시 */}
              <div className="soft-card p-6">
                <div className="mb-4 flex items-center justify-between">
                  <div>
                    <h3 className="text-lg font-bold text-slate-900">🔔 자동 추천 항목</h3>
                    <p className="text-xs text-slate-400 mt-1">재고 부족 알림을 켜둔 식재료 중 재고가 부족한 항목이 표시됩니다.</p>
                  </div>
                </div>
                {adoptedMsg && (
                  <div className="mb-3 rounded-2xl bg-[#F4F8F1] px-4 py-2.5 text-sm font-medium text-sage">{adoptedMsg}</div>
                )}
                {autoItems.length === 0 ? (
                  <div className="rounded-2xl bg-[#FCFCFC] py-6 text-center text-sm text-slate-400">현재 알림이 켜져 있고 재고가 부족한 식재료가 없어요.</div>
                ) : (
                  <div className="space-y-2">
                    {autoItems.map(item => (
                      <div key={item.id} className={`flex items-center gap-3 rounded-2xl border p-3.5 transition-all ${item.checked ? 'border-transparent bg-slate-100 opacity-60' : 'border-amber-200 bg-amber-50'}`}>
                        {/* 기능 2: 왼쪽 "+" 버튼 — 클릭 시 실제 체크리스트(ShoppingList manual row)에 즉시 등록 */}
                        <button type="button" onClick={() => adoptToChecklist(item)} disabled={adoptingId === item.id}
                          title="내 체크리스트에 추가"
                          className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-white text-amber-500 border border-amber-200 hover:bg-amber-500 hover:text-white transition-colors disabled:opacity-50">
                          <Plus size={16} />
                        </button>
                        <button onClick={() => handleToggle(item)} className="flex flex-1 items-center gap-3 text-left">
                          <span className={`flex h-9 w-9 shrink-0 items-center justify-center rounded-full ${item.checked ? 'bg-sage text-white' : 'bg-white text-amber-500'}`}><Check size={15} /></span>
                          <div>
                            <span className={`font-semibold ${item.checked ? 'text-slate-400 line-through' : 'text-slate-900'}`}>{item.name}</span>
                            <div className="mt-1 flex flex-wrap gap-2 text-xs">
                              <span className="rounded-full bg-white border border-amber-200 px-2.5 py-1 font-semibold text-amber-700">남은 재고 {item.remainingGrams ?? 0}g</span>
                              <span className="rounded-full bg-[#EDF7E7] border border-[#C8E4B8] px-2.5 py-1 font-semibold text-sage">추천 구매량 {Math.max(200, (item.remainingGrams ?? 0) < 50 ? 300 : 200)}g</span>
                            </div>
                          </div>
                        </button>
                      </div>
                    ))}
                  </div>
                )}
              </div>

              {/* 구매 완료 내역 (체크된 전체 항목) */}
              {items.some(i => i.checked) && (
                <div className="soft-card p-6">
                  <h3 className="text-lg font-bold text-slate-900 mb-4">✅ 구매 완료</h3>
                  <div className="space-y-2">
                    {items.filter(i => i.checked).map(item => (
                      <div key={item.id} className="flex items-center justify-between gap-4 rounded-2xl border border-transparent bg-slate-100 p-3.5 opacity-70">
                        <div className="flex items-center gap-3">
                          <span className="flex h-9 w-9 items-center justify-center rounded-full bg-sage text-white"><Check size={15} /></span>
                          <span className="font-semibold text-slate-400 line-through">{item.name}</span>
                        </div>
                        <button onClick={() => removeItem(item.id)} className="flex h-8 w-8 items-center justify-center rounded-full bg-white text-slate-400 hover:text-coral shadow-sm"><Trash2 size={14} /></button>
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </div>
          )}
        </section>
      </div>

      {/* #3: 체크 시 구매내역 반영 모달 */}
      <Modal open={!!checkModal} onClose={() => setCheckModal(null)} title="구매 완료 처리" className="max-w-sm">
        <div className="space-y-4">
          <p className="text-sm text-slate-500">
            <strong className="text-slate-900">{checkModal?.name}</strong>을(를) 구매 완료로 표시하면 구매내역(식재료)에 자동으로 등록됩니다.
          </p>
          <div className="grid grid-cols-2 gap-3">
            <div>
              <label className="mb-1 block text-xs font-bold text-slate-500">가격 (원)</label>
              <input type="number" min="0" step="0.01" className="input-base" placeholder="0" value={checkPrice} onChange={e => setCheckPrice(e.target.value)} />
            </div>
            <div>
              <label className="mb-1 block text-xs font-bold text-slate-500">용량 (g)</label>
              <input type="number" min="1" step="0.01" className="input-base" placeholder="200" value={checkGrams} onChange={e => setCheckGrams(e.target.value)} />
            </div>
          </div>
          <div className="flex gap-3 pt-1">
            <button onClick={() => setCheckModal(null)} className="flex-1 rounded-2xl border border-border px-5 py-3 font-semibold text-slate-500">취소</button>
            <button onClick={confirmCheck} disabled={confirming} className="flex-1 rounded-2xl bg-sage px-5 py-3 font-semibold text-white disabled:opacity-60">
              {confirming ? '처리 중...' : '구매 완료'}
            </button>
          </div>
        </div>
      </Modal>
    </div>
  );
}
